spring.application.name=spring-ai
server.port=8090
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3
#spring.ai.openai.api-key=${OPEN_API_KEY}
#spring.ai.openai.chat.options.model=gpt-4